{{ config(
    pre_hook="ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true",
    post_hook="GRANT SELECT ON TABLE {{ this }} TO ROLE TEST_DBT_ROLE"  
) }}

{{ config(
    tags=[var('TAG_FACT')]
) }}

WITH VOTES AS
(
SELECT ID
,NVL(IMDB_ID,'N/A') AS IMDB_ID
,NVL(IMDB_SCORE,0) AS IMDB_SCORE
,NVL(IMDB_VOTES,0) AS IMDB_VOTES
,NVL(TMDB_POPULARITY,0) AS TMDB_POPULARITY
,NVL(TMDB_SCORE,0) AS TMDB_SCORE
FROM
PROD.DBT_TRANSFORM.SCORES_VOTES_DIM
)

SELECT
TITLE
,TYPE
,DESCRIPTION
,RELEASE_YEAR
,VOTES.*
FROM PROD.DBT_TRANSFORM.SHOW_DETAILS_DIM DETAILS
LEFT JOIN
VOTES
ON
DETAILS.ID=VOTES.ID

