{{ config(
    database='DBT_PROD',
    tags=["stocks_batch"]
) }}

--CTE to get the highest value of the stock in 2 years
WITH MAX_HIGH AS (
SELECT 
ROUND(MAX(HIGH)) AS MAX_HIGH
,TICKER 
FROM DBT_STAGING.STOCK_MARKET_ADITYA.YAHOO_STOCKS_BATCH_DATA
WHERE DATE>=CURRENT_DATE - (365*2)
GROUP BY 2),

--Calculate the dates for the highs
INCLUDE_DATES AS
(SELECT 
M.TICKER
,B.DATE
,M.MAX_HIGH 
FROM 
{{ref('YAHOO_STOCKS_BATCH_DATA')}} B
INNER JOIN
MAX_HIGH M
ON
ROUND(B.HIGH)=ROUND(M.MAX_HIGH)
AND
B.TICKER=M.TICKER)

SELECT DISTINCT * FROM INCLUDE_DATES ORDER BY TICKER ASC, DATE ASC