{{ config(
    database='DBT_PROD',
    tags=["stocks_streaming"]
) }}


WITH HOURLY_DATA AS
(SELECT DISTINCT
SYMBOL
,YEAR(INGESTED_TIME) AS YEAR
,MONTH(INGESTED_TIME) AS MONTH
,DAY(INGESTED_TIME) AS DAY
,HOUR(INGESTED_TIME) AS HOUR
,OPEN
,HIGH
,LOW
,CLOSE
FROM {{ref('YAHOO_STOCKS_STREAMING_DATA')}}
--WHERE TRIM(SYMBOL)='NVDA'
),

PREVIOUS_OPEN_CALC AS(
    SELECT *,
    CASE
        WHEN PREVIOUS_OPEN_SAME_DAY IS NOT NULL THEN
            CASE
                WHEN OPEN>PREVIOUS_OPEN_SAME_DAY THEN 'BEARISH'
                WHEN OPEN<PREVIOUS_OPEN_SAME_DAY THEN 'BULLISH'
                ELSE 'SIDEWAYS'
            END
        ELSE
            CASE
                WHEN OPEN>PREVIOUS_OPEN_DIFF_DAY THEN 'BEARISH'
                WHEN OPEN<PREVIOUS_OPEN_DIFF_DAY THEN 'BULLISH'
                ELSE 'SIDEWAYS'
            END
        END AS STOCK_STATUS
    FROM
        (SELECT *,
        LAG(OPEN) OVER (PARTITION BY SYMBOL ORDER BY GLOBAL_RANK ASC) AS PREVIOUS_OPEN_DIFF_DAY
        FROM
            (SELECT *
            ,LAG(OPEN) OVER (PARTITION BY SYMBOL,MONTH,DAY ORDER BY HOUR ASC ) AS PREVIOUS_OPEN_SAME_DAY
            ,ROW_NUMBER() OVER(PARTITION BY SYMBOL ORDER BY YEAR ASC, MONTH ASC,DAY ASC,HOUR ASC) AS GLOBAL_RANK
            FROM HOURLY_DATA)))

SELECT *
EXCLUDE(PREVIOUS_OPEN_SAME_DAY,PREVIOUS_OPEN_DIFF_DAY,GLOBAL_RANK,STOCK_STATUS)
,CASE
    WHEN PREVIOUS_OPEN_SAME_DAY IS NULL AND PREVIOUS_OPEN_DIFF_DAY IS NULL THEN 'UNCLASSIFIED'
    ELSE STOCK_STATUS
END AS STOCK_STATUS
FROM PREVIOUS_OPEN_CALC
ORDER BY SYMBOL ASC, YEAR ASC, MONTH ASC, DAY ASC, HOUR ASC